// data/pest.ts
export const pests = [
  {
    name: "Ants",
    slug: "ants",
    icon: "/icons/ant.png",
    summary: "Small but persistent insects that invade kitchens and living spaces, often attracted to food and moisture.",
    prevention: "Seal cracks, keep food in airtight containers, and clean up spills promptly.",
    treatment: "Use ant baits, natural deterrents like vinegar or citrus, or consult pest control professionals.",
    funFact: "Some ant species farm aphids for their honeydew!",
  },
  {
    name: "Cockroaches",
    slug: "cockroaches",
    icon: "/icons/cockroach.png",
    summary: "Resilient pests that thrive in warm, dark, and damp environments, capable of spreading bacteria.",
    prevention: "Keep kitchens clean, store food securely, and seal gaps in walls and cabinets.",
    treatment: "Gel baits, traps, and professional extermination are effective.",
    funFact: "Cockroaches can survive without their heads for up to a week!",
  },
  {
    name: "Spiders",
    slug: "spiders",
    icon: "/icons/spider.png",
    summary: "Web-spinning arachnids that often appear indoors, generally harmless but can cause fear.",
    prevention: "Remove webs regularly, reduce clutter, and seal entry points.",
    treatment: "Catch and release, vacuum webs, or use spider deterrent sprays.",
    funFact: "Some spiders can eat twice their body weight in one meal!",
  },
  {
    name: "Termites",
    slug: "termites",
    icon: "/icons/termite.png",
    summary: "Wood-destroying pests that can silently damage homes and structures over time.",
    prevention: "Reduce wood-to-soil contact, repair leaks, and remove old wood debris.",
    treatment: "Professional termite treatments, baits, and chemical barriers are most effective.",
    funFact: "Termite colonies can number in the millions!",
  },
  {
    name: "Rats",
    slug: "rats",
    icon: "/icons/rat.png",
    summary: "Large rodents that chew on structures, wires, and food, posing health risks.",
    prevention: "Seal entry points, remove food sources, and keep areas clean.",
    treatment: "Traps, rodenticides, and professional removal services.",
    funFact: "Rats are highly intelligent and can remember solutions to mazes.",
  },
  {
    name: "Mice",
    slug: "mice",
    icon: "/icons/mouse.png",
    summary: "Small rodents that contaminate food and nesting areas, often in hidden spaces.",
    prevention: "Seal small holes, store food securely, and maintain cleanliness.",
    treatment: "Snap traps, bait stations, or professional pest control services.",
    funFact: "A single pair of mice can produce hundreds of offspring in a year!",
  },
  {
    name: "Bed Bugs",
    slug: "bed-bugs",
    icon: "/icons/bed-bug.png",
    summary: "Small, biting insects that infest beds, mattresses, and furniture.",
    prevention: "Inspect second-hand furniture, wash bedding regularly, and reduce clutter.",
    treatment: "Heat treatments, mattress encasements, and professional extermination.",
    funFact: "Bed bugs can survive several months without feeding!",
  },
  {
    name: "Fleas",
    slug: "fleas",
    icon: "/icons/flea.png",
    summary: "Tiny parasitic insects that affect pets and can bite humans.",
    prevention: "Regularly treat pets, vacuum carpets, and wash bedding.",
    treatment: "Flea collars, sprays, and professional pest control services.",
    funFact: "Fleas can jump over 100 times their own body length!",
  },
  {
    name: "Wasps",
    slug: "wasps",
    icon: "/icons/wasp.png",
    summary: "Aggressive stinging insects found around homes, gardens, and trash.",
    prevention: "Keep garbage sealed, avoid leaving sugary drinks outside, and seal entry points.",
    treatment: "Trap removal, careful nest removal, or professional extermination.",
    funFact: "Wasps can recognize faces and communicate with their colony!",
  },
  {
    name: "Bees",
    slug: "bees",
    icon: "/icons/bee.png",
    summary: "Important pollinators that need careful handling when nests are near homes.",
    prevention: "Plant bee-friendly flowers away from doorways, and avoid disturbing hives.",
    treatment: "Call a professional beekeeper for safe removal.",
    funFact: "Bees communicate through a “waggle dance” to show food locations.",
  },
  {
    name: "Mosquitoes",
    slug: "mosquitoes",
    icon: "/icons/mosquito.png",
    summary: "Biting insects that can spread diseases like malaria and dengue.",
    prevention: "Remove standing water, use repellents, and install screens.",
    treatment: "Mosquito traps, repellents, and professional control services.",
    funFact: "Only female mosquitoes bite humans to get protein for egg-laying.",
  },
  {
    name: "Silverfish",
    slug: "silverfish",
    icon: "/icons/silverfish.png",
    summary: "Moisture-loving insects that damage paper, books, and fabrics.",
    prevention: "Reduce humidity, store papers in sealed containers, and clean regularly.",
    treatment: "Sticky traps, dehumidifiers, and professional pest control if infestations are heavy.",
    funFact: "Silverfish can live up to 3 years without food!",
  },
];
